### ISSUE TITLE
Some calendar date events are failing with server error

### ISSUE THREAD

**Issue by denshu-arte** [brianglass/orthocal-python#6]
Hello, there. Found a set of events where the Orthocal API doesn't work (returns server error).

List of API calls that don't work (there might probably be more):

- https://orthocal.info/api/julian/2024/4/8/
- https://orthocal.info/api/julian/2024/4/
- https://orthocal.info/api/gregorian/2024/3/26/
- https://orthocal.info/api/gregorian/2024/3/
- https://orthocal.info/api/julian/2025/4/
- https://orthocal.info/api/julian/2025/4/8/

Some notes (added it in case it's helpful with finding the reason for the bug):

- Though julian/2025/4/8/ fails, gregorian/2025/3/26/ works fine.
- Also julian/2024/4/ seems to have failed because there's an error in calculation of julian/2024/4/8/ i.e. month calculation seems to fail because one day of the sequence cannot be calculated.

Hope the issue can be resolved soon!

Also, could you please give me some information on when you are planning to look into this issue? I'm working on a personal project using this API and would like to know if I could continue soon or should postpone it for a bit.

**Comment by denshu-arte** [comment]
Hey @brianglass 
Any thoughts/updates on this?

**Comment by brianglass** [comment]
@denshu-arte, thank you for the bug report. I just deployed a fix for these this afternoon. Please try again and let me know if it is resolved. The error occurs if there is a Leave-taking of Annunciation that occurs on a non-liturgy day. You can review the commit here: https://github.com/brianglass/orthocal-python/commit/abedc58e13dd03eb182322eb4a0e6599289b32c2

**Comment by denshu-arte** [comment]
@brianglass yes, it works now. Thank you for the fix. I'll be closing the issue now.
